language: node_js
node_js:
  - "stable"

before_install:
  - cd web-components

script:
=======
  - stable
cache:
  directories:
  - node_modules
script:
  - npm run lint
  - npm run test
  - npm run build

deploy:
  provider: pages
  github_token: $repo_token
=======
  skip_cleanup: true
  github_token: 
  local_dir: build
  on:
    branch:
      - master
      - frontend_01
